/* Данные Tennis Injury Terminal.
   Обновление: python update.py — освежает рейтинги и метку времени,
   а новые записи RotoWire печатает заготовками для вставки в NEWS. */

/* Когда данные последний раз сверяли с источниками (MSK). */
const UPDATED = "2026-09-04 18:58";

/* Турнир, ради которого считается вкладка риска. */
const EVENT = {name:"US Open", mainDraw:"2026-08-30"};

const UI = {
  en:{
    tagline:"ATP & WTA top 250 · injuries, withdrawals, medical timeouts",
    search:"Search player or text", reset:"Reset", clear:"Clear", live:"Live", top:"Back to top",
    wire:"Wire", filter:"Filter", index:"Players", chart:"Activity, last 14 days",
    chartHint:"records per day", sorted:"newest first",
    tabAtp:"ATP · men", tabWta:"WTA · women", tabWd:"Withdrawals", tabFade:"Fade list",
    tabMatches:"Matches", tabRanking:"Ranking",
    tabAtpSub:"top 250", tabWtaSub:"top 250", tabWdSub:"entry lists", tabFadeSub:"this & next week",
    tabMatchesSub:"this week", tabRankingSub:"top 500",
    today:"today", tomorrow:"tomorrow", noMatches:"No matches scheduled for this day.",
    chartMatches:"Matches by day", chartMatchesHint:"schedule published so far",
    matchesWeek:"Matches", matchesToday:"Today", events:"tournaments",
    colPos:"#", colMove:"±", colPlayer:"Player", colPts:"Points", colDef:"Defending",
    rankNote:"“Defending” is what the player loses at the 2026 US Open unless they match last year's result — from the tournament's own seeding tables, so only seeds have a number.",
    showMore:"Show more", profAge:"age", profPts:"points", profDefend:"defending",
    nextMatch:"Next match", noRecords:"No injury records for this player.",
    photoCredit:"photo: Wikipedia", historySix:"Signals, last six months",
    olderHidden:"older records hidden", vs:"vs",
    tgCaption:"Medical timeouts, live",
    fadeLead:"Players carrying a fresh medical signal into the US Open — ranked by how heavy and how recent that signal is. A ranking of physical risk, not a prediction of results.",
    fadeWarn:"Not betting advice and not a tip. The score is arithmetic over public injury reports; it knows nothing about the opponent, the surface, the schedule or the price. 18+.",
    riskScore:"risk score", signals:"signals", howTitle:"How the score works",
    howBody:"Every medical signal has a weight, faded by how long ago it happened (21 days to zero). Two or more signals in three weeks add a repeat bonus.",
    statusSeed:"seed", statusIn:"in the draw", statusLikely:"main draw by ranking",
    statusNote:"draw status", candidates:"Candidates", avgScore:"avg score",
    sigRetired:"retired mid-match", sigMto:"medical timeout", sigIllness:"illness",
    sigWd_mid:"pulled out at the event", sigWd_pre:"withdrew before the event",
    sigRest:"rest / undisclosed", sigReturn:"back from a layoff", sigCondition:"chronic condition",
    all:"All records", injury:"Injuries", withdrawal:"Withdrawals",
    returning:"Returning", condition:"Status", starred:"Watchlist",
    men:"Men", women:"Women",
    kInjury:"Injury", kWithdrawal:"Withdrawal", kReturning:"Returning", kCondition:"Status",
    sTotal:"Records", sPlayers:"Players", sInj:"Injuries", sWd:"Withdrawals",
    lastRec:"latest", events:"tournaments", ofTotal:"of this tab",
    empty:"Nothing matches this filter.", emptyHint:"Try another filter or clear the search.",
    kicker:"Live medical wire",
    heroTitle:"Who is <span class='hl'>hurt</span>,<br>who is out, who is back.",
    heroLead:"Injuries, retirements and entry-list changes across the ATP and WTA top 250 — every line carries the source it came from.",
    ctaFeed:"Open the feed", ctaTg:"Live medical timeouts", tgName:"Live medical timeouts",
    rank:"rank", replacedBy:"IN:", outOfTop:"outside top 250",
    updated:"updated", stale:"data may be stale", close:"Close",
    autoNote:"auto", autoHint:"added automatically, wording not edited by hand",
    copy:"Copy for post", copied:"Copied to clipboard",
    history:"Signal history", openCard:"open player card",
    btTitle:"Model check", btRate:"signals repeated within 14 days",
    btBody:"How often a medical signal was followed by another one from the same player inside two weeks. This is what the repeat bonus is built on.",
    btMain:"US Open main draw starts 30 August — match results land here after the next data update.",
    afterRepeat:"repeat after", afterFirst:"first signal", days:"days",
    promoTitle:"Medical timeouts, live", promoLead:"Medical timeouts, the moment they happen.",
    tgGo:"Open the channel →",
    b1:"<b>Live alerts</b> — the moment a player calls the trainer",
    b2:"<b>Who took it</b> — name, score, who is serving",
    b3:"<b>What happened next</b> — held or lost the service game",
    b4:"<b>Odds</b> — before the break and when the line reopens",
    note:"Free. ATP, WTA, Challengers, ITF and doubles.",
    footNote:"Compiled from public reports · rankings via live-tennis.eu · not medical advice.",
    months:["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],
    ago:d => d === 0 ? "today" : d === 1 ? "1 day ago" : d + " days ago",
  },
  ru:{
    tagline:"ATP и WTA топ-250 · травмы, снятия, медицинские перерывы",
    search:"Поиск по игроку или тексту", reset:"Сброс", clear:"Очистить", live:"Онлайн", top:"Наверх",
    wire:"Лента", filter:"Фильтр", index:"Игроки", chart:"Активность за 14 дней",
    chartHint:"записей в день", sorted:"сначала новые",
    tabAtp:"ATP · мужчины", tabWta:"WTA · женщины", tabWd:"Снятия", tabFade:"Против кого ставить",
    tabMatches:"Матчи", tabRanking:"Рейтинг",
    tabAtpSub:"топ-250", tabWtaSub:"топ-250", tabWdSub:"заявки турниров", tabFadeSub:"эта и следующая неделя",
    tabMatchesSub:"неделя", tabRankingSub:"топ-500",
    today:"сегодня", tomorrow:"завтра", noMatches:"На этот день матчей нет.",
    chartMatches:"Матчи по дням", chartMatchesHint:"расписание опубликовано на",
    matchesWeek:"Матчей", matchesToday:"Сегодня",
    colPos:"#", colMove:"±", colPlayer:"Игрок", colPts:"Очки", colDef:"Защищает",
    rankNote:"«Защищает» — очки, которые игрок теряет по итогам US Open 2026, если не повторит прошлогодний результат. Взято из посевных таблиц самого турнира, поэтому число есть только у сеяных.",
    showMore:"Показать ещё", profAge:"возраст", profPts:"очки", profDefend:"к защите",
    nextMatch:"Ближайший матч", noRecords:"Травм по этому игроку в базе нет.",
    photoCredit:"фото: Википедия", historySix:"Сигналы за последние полгода",
    olderHidden:"записи старше полугода скрыты", vs:"против",
    tgCaption:"Медицинские тайм-ауты в лайв режиме",
    fadeLead:"Игроки, которые подошли к US Open со свежим медицинским сигналом — отсортированы по тому, насколько сигнал тяжёлый и насколько свежий. Это рейтинг физического риска, а не прогноз результата.",
    fadeWarn:"Не ставка и не прогноз. Оценка — арифметика по открытым сообщениям о травмах: она ничего не знает о сопернике, покрытии, сетке и коэффициенте. 18+.",
    riskScore:"риск", signals:"сигналы", howTitle:"Как считается оценка",
    howBody:"У каждого медицинского сигнала свой вес, который затухает со временем (21 день до нуля). Два и более сигнала за три недели дают надбавку за повторность.",
    statusSeed:"посев", statusIn:"в сетке", statusLikely:"основная сетка по рейтингу",
    statusNote:"статус в сетке", candidates:"Кандидатов", avgScore:"средний риск",
    sigRetired:"снятие по ходу матча", sigMto:"медицинский перерыв", sigIllness:"недомогание",
    sigWd_mid:"снятие уже на турнире", sigWd_pre:"снятие до турнира",
    sigRest:"отдых / без причины", sigReturn:"возвращение после паузы", sigCondition:"хроническая проблема",
    all:"Все записи", injury:"Травмы", withdrawal:"Снятия",
    returning:"Возвращения", condition:"Статус", starred:"Избранное",
    men:"Мужчины", women:"Женщины",
    kInjury:"Травма", kWithdrawal:"Снятие", kReturning:"Возвращение", kCondition:"Статус",
    sTotal:"Записей", sPlayers:"Игроков", sInj:"Травм", sWd:"Снятий",
    lastRec:"последняя", events:"турниров", ofTotal:"от вкладки",
    empty:"По этому фильтру ничего нет.", emptyHint:"Попробуйте другой фильтр или очистите поиск.",
    kicker:"Медицинская лента",
    heroTitle:"Кто <span class='hl'>травмирован</span>,<br>кто снялся, кто вернулся.",
    heroLead:"Травмы, снятия по ходу матчей и изменения в заявках турниров у топ-250 ATP и WTA — по каждой записи есть ссылка на источник.",
    ctaFeed:"Смотреть ленту", ctaTg:"Live medical timeouts", tgName:"Live medical timeouts",
    rank:"рейтинг", replacedBy:"Замена:", outOfTop:"вне топ-250",
    updated:"обновлено", stale:"данные могли устареть", close:"Закрыть",
    autoNote:"авто", autoHint:"добавлено автоматически, формулировка не выверена руками",
    copy:"Скопировать для поста", copied:"Скопировано в буфер",
    history:"История сигналов", openCard:"открыть карточку игрока",
    btTitle:"Проверка модели", btRate:"сигналов повторились за 14 дней",
    btBody:"Как часто за медицинским сигналом в течение двух недель следовал ещё один у того же игрока. Именно на этом держится надбавка за повторность.",
    btMain:"Основная сетка US Open стартует 30 августа — результаты матчей появятся здесь после следующего обновления данных.",
    afterRepeat:"повтор через", afterFirst:"первый сигнал", days:"дн.",
    promoTitle:"Медицинские тайм-ауты в прямом эфире",
    promoLead:"Медицинские тайм-ауты в момент, когда они происходят.",
    tgGo:"Перейти в канал →",
    b1:"<b>Мгновенные алерты</b> — как только игрок зовёт врача",
    b2:"<b>Кто взял</b> — имя, счёт, чья подача",
    b3:"<b>Что было дальше</b> — удержал или проиграл свою подачу",
    b4:"<b>Коэффициенты</b> — до перерыва и когда линия открылась",
    note:"Бесплатно. ATP, WTA, челленджеры, ITF и пары.",
    footNote:"Собрано из открытых источников · рейтинг по live-tennis.eu · не медицинская рекомендация.",
    months:["янв","фев","мар","апр","май","июн","июл","авг","сен","окт","ноя","дек"],
    ago:d => d === 0 ? "сегодня" : d === 1 ? "вчера" : d + " дн. назад",
  },
};
const t = k => UI[LANG][k];

/* Турниры: код → название для карточек. */
const TOURN = {
  USO:"US Open", CIN:"Cincinnati", WST:"Winston-Salem", MTL:"Montreal", TOR:"Toronto",
  MTY:"Monterrey", STU:"Stuttgart", AO:"Australian Open", RG:"Roland Garros", WIM:"Wimbledon",
};

/* tour — atp/wta, rank — место в рейтинге на 25.08.2026 (live-tennis.eu),
   repl — кто вошёл в сетку вместо снявшегося. */
const NEWS = [
  {ts:"2026-09-01 12:00", who:"Corentin Moutet", whoRu:"Корентен Муте", tour:"atp", rank:62, code:"USO", kind:"injury", sig:"retired", auto:true,
   en:"retired down 7-6 (4). 6-4, 3-0 to Dane Sweeny in the first round of the US Open on Tuesday.",
   ru:"retired down 7-6 (4). 6-4, 3-0 to Dane Sweeny in the first round of the US Open on Tuesday.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-30 12:00", who:"Marin Cilic", whoRu:null, tour:"atp", rank:81, code:"USO", kind:"withdrawal", sig:"wd_mid", auto:true,
   en:"withdrew from the US Open before his first round match.",
   ru:"снялся с <b>US Open</b> перед матчем первого круга, причина не раскрыта.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-30 12:00", who:"Casper Ruud", whoRu:"Каспер Рууд", tour:"atp", rank:20, code:"USO", kind:"withdrawal", sig:"wd_mid",
   en:"withdrew from the US Open before his first round match.",
   ru:"снялся с <b>US Open</b> перед матчем первого круга, причина не раскрыта.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-29 12:00", who:"Ethan Quinn", whoRu:"Итан Куинн", tour:"atp", rank:61, code:"USO", kind:"injury", sig:"wd_mid", auto:true,
   en:"isn't in the US Open draw.",
   ru:"isn't in the US Open draw.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-29 12:00", who:"Gabriel Diallo", whoRu:"Габриэль Диалло", tour:"atp", rank:114, code:"USO", kind:"injury", sig:"wd_mid", auto:true,
   en:"isn't in the US Open draw.",
   ru:"isn't in the US Open draw.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-29 12:00", who:"Sonay Kartal", whoRu:null, tour:"wta", rank:124, code:"USO", kind:"injury", sig:"wd_mid", auto:true,
   en:"isn't in the US Open draw.",
   ru:"isn't in the US Open draw.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-29 12:00", who:"Veronika Kudermetova", whoRu:null, tour:"atp", rank:null, code:"USO", kind:"withdrawal", sig:"wd_mid", auto:true,
   en:"isn't in the US Open draw.",
   ru:"isn't in the US Open draw.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-29 12:00", who:"Emma Raducanu", whoRu:"Эмма Радукану", tour:"wta", rank:70, code:"USO", kind:"injury", sig:"wd_mid", auto:true,
   en:"isn't in the US Open draw.",
   ru:"isn't in the US Open draw.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-29 12:00", who:"Victoria Mboko", whoRu:"Виктория Мбоко", tour:"wta", rank:15, code:"USO", kind:"injury", sig:"wd_mid", auto:true,
   en:"isn't in the US Open draw.",
   ru:"isn't in the US Open draw.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-29 12:00", who:"Ajla Tomljanovic", whoRu:"Айла Томлянович", tour:"wta", rank:103, code:"USO", kind:"injury", sig:"wd_mid", auto:true,
   en:"isn't in the US Open draw.",
   ru:"isn't in the US Open draw.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-29 12:00", who:"Ons Jabeur", whoRu:null, tour:"atp", rank:null, code:"USO", kind:"injury", sig:"wd_mid", auto:true,
   en:"isn't in the US Open draw.",
   ru:"isn't in the US Open draw.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-29 12:00", who:"Jaqueline Cristian", whoRu:"Жаклин Кристиан", tour:"wta", rank:44, code:"USO", kind:"injury", sig:"wd_mid", auto:true,
   en:"isn't in the US Open draw.",
   ru:"isn't in the US Open draw.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-26 12:00", who:"Sebastian Baez", whoRu:null, tour:"atp", rank:51, code:"WST", kind:"injury", sig:"retired", auto:true,
   en:"retired down 6-2, 4-0 to Juan Manuel Cerundolo in the third round of Winston-Salem on Wednesday.",
   ru:"снялся при 6-2 4-0 против Juan Manuel Cerundolo в третьем круге <b>Уинстон-Сейлема</b>, причина не раскрыта.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-26 12:00", who:"Maria Timofeeva", whoRu:"Мария Тимофеева", tour:"wta", rank:86, code:"MTY", kind:"injury", sig:"wd_mid",
   en:"withdrew from Monterrey before her second round match against Ann Li.",
   ru:"снялась с <b>Монтеррея</b> перед матчем второго круга против Ann Li из-за <span class='flag'>спины</span>.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-25 12:00", who:"Anastasia Potapova", whoRu:null, tour:"wta", rank:25, code:"MTY", kind:"injury", sig:"wd_mid", auto:true,
   en:"withdrew from Monterrey before her first match.",
   ru:"снялась с <b>Монтеррея</b> перед матчем first из-за <span class='flag'>спины</span>.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  /* ─────────── ATP ─────────── */
  {ts:"2026-08-24 14:10", who:"Joao Fonseca", whoRu:"Жоао Фонсека", tour:"atp", rank:26, code:"USO", kind:"withdrawal", sig:"wd_mid",
   en:"withdrew from the <b>US Open</b> before his first-round match with an <span class='flag'>abdominal injury</span> — the same problem that stopped him in Cincinnati six days earlier.",
   ru:"снялся с <b>US Open</b> перед матчем первого круга из-за <span class='flag'>травмы живота</span> — та же проблема остановила его в Цинциннати шестью днями ранее.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-24 12:30", who:"Pablo Carreno Busta", whoRu:"Пабло Карреньо Буста", tour:"atp", rank:66, code:"WST", kind:"injury", sig:"retired",
   en:"retired with a <span class='flag'>back problem</span> down 4-6 0-3 to Adolfo Daniel Vallejo in round one of <b>Winston-Salem</b>.",
   ru:"снялся с <span class='flag'>проблемой спины</span> при 4-6 0-3 против Адольфо Даниэля Вальехо в первом круге <b>Уинстон-Сейлема</b>.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-24 09:30", who:"Vit Kopriva", whoRu:"Вит Коприва", tour:"atp", rank:69, code:"WST", kind:"withdrawal", sig:"wd_pre",
   en:"is out of <b>Winston-Salem</b>, reason not disclosed.",
   ru:"выбыл из <b>Уинстон-Сейлема</b>, причина не раскрыта.",
   repl:"Herbert (LL, vs Sonego)", replRu:"Эрбер (LL, против Сонего)",
   src:"https://x.com/EntryLists", srcName:"@EntryLists"},
  {ts:"2026-08-23 12:20", who:"Marton Fucsovics", whoRu:"Мартон Фучович", tour:"atp", rank:122, code:"WST", kind:"injury", sig:"wd_mid",
   en:"withdrew from <b>Winston-Salem</b> before round one with a <span class='flag'>shoulder problem</span>, ten days after retiring in Cincinnati with his back.",
   ru:"снялся с <b>Уинстон-Сейлема</b> перед первым кругом из-за <span class='flag'>плеча</span> — через десять дней после снятия в Цинциннати из-за спины.",
   repl:"Lucky loser", replRu:"Счастливый неудачник",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-23 11:50", who:"Dino Prizmic", whoRu:"Дино Призмич", tour:"atp", rank:102, code:"WST", kind:"injury", sig:"wd_mid",
   en:"withdrew from <b>Winston-Salem</b> before his first-round match with a <span class='flag'>hip problem</span>.",
   ru:"снялся с <b>Уинстон-Сейлема</b> перед матчем первого круга из-за <span class='flag'>бедра</span>.",
   repl:"Lucky loser", replRu:"Счастливый неудачник",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-23 11:30", who:"Valentin Royer", whoRu:"Валентен Руайе", tour:"atp", rank:75, code:"WST", kind:"withdrawal", sig:"rest",
   en:"withdrew from <b>Winston-Salem</b> before round one, listed as rest.",
   ru:"снялся с <b>Уинстон-Сейлема</b> перед первым кругом, причина указана как отдых.",
   repl:"Lucky loser", replRu:"Счастливый неудачник",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-22 10:05", who:"Bonzi / Bellucci", whoRu:"Бонзи / Беллуччи", tour:"atp", rank:96, code:"WST", kind:"returning", sig:"return",
   en:"both entered <b>Winston-Salem</b> as alternates while climbing back from injuries picked up at Wimbledon.",
   ru:"оба попали в основную сетку <b>Уинстон-Сейлема</b> как запасные, возвращаясь после травм, полученных на Уимблдоне.",
   src:"https://lastwordonsports.com/tennis/2026/08/22/withdraw-atp-winston-salem/", srcName:"Last Word"},
  {ts:"2026-08-22 10:00", who:"Juncheng Shang", whoRu:"Шан Цзюнчэн", tour:"atp", rank:228, code:"WST", kind:"returning", sig:"return",
   en:"skipped <b>Winston-Salem</b> to stay fit for best-of-five in New York. Comeback began in Washington on a protected ranking; already beat Rublev.",
   ru:"пропустил <b>Уинстон-Сейлем</b>, чтобы сохранить форму под пятисетовый формат. Возвращение начал в Вашингтоне по защищённому рейтингу, уже обыграл Рублёва.",
   src:"https://lastwordonsports.com/tennis/2026/08/22/withdraw-atp-winston-salem/", srcName:"Last Word"},
  {ts:"2026-08-21 14:35", who:"Holger Rune", whoRu:"Хольгер Руне", tour:"atp", rank:133, code:"USO", kind:"withdrawal", sig:"wd_pre",
   en:"will miss the <b>US Open</b>. No official match since rupturing his left <span class='flag'>Achilles</span> in October; chose not to return at a Slam.",
   ru:"пропустит <b>US Open</b>. Не играл с октября, когда порвал левое <span class='flag'>ахиллово сухожилие</span>; решил не возвращаться на шлеме.",
   repl:"Facundo Diaz Acosta", replRu:"Факундо Диас Акоста",
   src:"https://www.tennis365.com/tennis-news/us-open-withdrawal-list-2026-14-stars-out", srcName:"Tennis365"},
  {ts:"2026-08-21 14:20", who:"Jack Draper", whoRu:"Джек Дрейпер", tour:"atp", rank:141, code:"USO", kind:"withdrawal", sig:"wd_pre",
   en:"is out of the <b>US Open</b> with <span class='flag'>bone bruising in his left arm</span>, the problem that has run through his season.",
   ru:"вне <b>US Open</b> из-за <span class='flag'>ушиба кости левой руки</span> — проблема тянется через весь сезон.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire / Guardian"},
  {ts:"2026-08-21 11:00", who:"Jannik Sinner", whoRu:"Янник Синнер", tour:"atp", rank:1, code:"USO", kind:"withdrawal", sig:"wd_mid",
   en:"withdrew from the <b>US Open</b> with a <span class='flag'>right knee</span> issue. No match since the Wimbledon final on 12 July; first Slam missed since 2019.",
   ru:"снялся с <b>US Open</b> из-за <span class='flag'>правого колена</span>. Не играл с финала Уимблдона 12 июля; первый пропущенный шлем с 2019 года.",
   repl:"Carlos Taberner (PR)", replRu:"Карлос Табернер (PR)",
   src:"https://www.espn.com/tennis/story/_/id/49681192/jannik-sinner-withdraws-us-open-due-knee-injury", srcName:"ESPN"},
  {ts:"2026-08-20 16:00", who:"Carlos Alcaraz", whoRu:"Карлос Алькарас", tour:"atp", rank:3, code:"USO", kind:"returning", sig:"return",
   en:"confirmed his <b>US Open</b> return after four months out with a <span class='flag'>right wrist</span> injury. Missed Roland Garros, Wimbledon, Toronto and Cincinnati.",
   ru:"подтвердил возвращение на <b>US Open</b> после четырёх месяцев вне тура из-за <span class='flag'>правого запястья</span>. Пропустил Ролан Гаррос, Уимблдон, Торонто и Цинциннати.",
   src:"https://www.usopen.org/en_US/news/articles/2026-08-20/carlos_alcaraz_announces_return_from_injury_at_2026_us_open.html", srcName:"usopen.org"},
  {ts:"2026-08-20 12:10", who:"Alejandro Davidovich Fokina", whoRu:"Алехандро Давидович Фокина", tour:"atp", rank:27, code:"USO", kind:"withdrawal", sig:"wd_mid",
   en:"withdrew from the <b>US Open</b> with a <span class='flag'>back injury</span> that also cost him Montreal and Cincinnati.",
   ru:"снялся с <b>US Open</b> из-за <span class='flag'>травмы спины</span>, из-за неё же пропустил Монреаль и Цинциннати.",
   repl:"Alexei Popyrin", replRu:"Алексей Попырин",
   src:"https://www.tennis365.com/tennis-news/us-open-withdrawal-list-2026-14-stars-out", srcName:"Tennis365"},
  {ts:"2026-08-19 16:00", who:"Nick Kyrgios", whoRu:"Ник Кирьос", tour:"atp", rank:null, code:"USO", kind:"condition", sig:"condition", out:true,
   en:"has been <span class='flag'>suspended</span> after testing positive in-competition for cocaine at the Mallorca Championships in June.",
   ru:"<span class='flag'>отстранён</span> после положительной допинг-пробы на кокаин, взятой на турнире в Мальорке в июне.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire / NYT"},
  {ts:"2026-08-19 12:00", who:"Ethan Quinn", whoRu:"Итан Куинн", tour:"atp", rank:61, code:"USO", kind:"withdrawal", sig:"wd_pre",
   en:"withdrew from the <b>US Open</b> entry list.",
   ru:"снялся с заявки на <b>US Open</b>.",
   repl:"Martin Damm", replRu:"Мартин Дамм",
   src:"https://www.tennis365.com/tennis-news/us-open-withdrawal-list-2026-14-stars-out", srcName:"Tennis365"},
  {ts:"2026-08-19 11:40", who:"Emilio Nava", whoRu:"Эмилио Нава", tour:"atp", rank:111, code:"USO", kind:"withdrawal", sig:"wd_pre",
   en:"withdrew from the <b>US Open</b> entry list, one of the first two ATP withdrawals.",
   ru:"снялся с заявки на <b>US Open</b>, один из первых двух снявшихся у мужчин.",
   repl:"Benjamin Bonzi", replRu:"Бенжамен Бонзи",
   src:"https://www.tennis365.com/tennis-news/us-open-withdrawal-list-2026-14-stars-out", srcName:"Tennis365"},
  {ts:"2026-08-18 16:30", who:"Gabriel Diallo", whoRu:"Габриэль Диалло", tour:"atp", rank:114, code:"USO", kind:"withdrawal", sig:"wd_mid",
   en:"withdrew from the <b>US Open</b> after retiring with a <span class='flag'>leg problem</span> against Darderi in Montreal.",
   ru:"снялся с <b>US Open</b> после того, как в Монреале снялся по ходу матча против Дардери из-за <span class='flag'>ноги</span>.",
   repl:"Yibing Wu", replRu:"У Ибин",
   src:"https://www.tennis365.com/tennis-news/us-open-withdrawal-list-2026-14-stars-out", srcName:"Tennis365"},
  {ts:"2026-08-18 14:00", who:"Joao Fonseca", whoRu:"Жоао Фонсека", tour:"atp", rank:26, code:"CIN", kind:"withdrawal", sig:"wd_mid",
   en:"withdrew before his third-round match in <b>Cincinnati</b> against O'Connell with an <span class='flag'>abdominal injury</span>.",
   ru:"снялся перед матчем третьего круга в <b>Цинциннати</b> против О'Коннелла из-за <span class='flag'>травмы живота</span>.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-16 15:10", who:"Casper Ruud", whoRu:"Каспер Рууд", tour:"atp", rank:20, code:"CIN", kind:"injury", sig:"retired",
   en:"retired with a <span class='flag'>back problem</span> down 5-7 1-2 to O'Connell in round two of <b>Cincinnati</b>.",
   ru:"снялся с <span class='flag'>проблемой спины</span> при 5-7 1-2 против О'Коннелла во втором круге <b>Цинциннати</b>.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-16 10:30", who:"Novak Djokovic", whoRu:"Новак Джокович", tour:"atp", rank:5, code:"CIN", kind:"condition", sig:"condition",
   en:"said he has lived for years with a health issue that is hard to manage in heat and humidity, and that it caused the <span class='flag'>medical timeout</span>.",
   ru:"сказал, что годами живёт с проблемой, тяжело переносимой при жаре и влажности, и что именно она вызвала <span class='flag'>медицинский перерыв</span>.",
   src:"https://www.nbcnews.com/sports/tennis/novak-djokovic-reveals-health-issue-ouster-cincinnati-open-rcna592768", srcName:"NBC News"},
  {ts:"2026-08-15 21:40", who:"Novak Djokovic", whoRu:"Новак Джокович", tour:"atp", rank:5, code:"CIN", kind:"injury", sig:"mto",
   en:"took a <span class='flag'>medical timeout</span> in round two in <b>Cincinnati</b> after an 18-minute service game. Appeared to vomit on court. Lost 2-6 6-4 6-4.",
   ru:"взял <span class='flag'>медицинский перерыв</span> во втором круге в <b>Цинциннати</b> после 18-минутного гейма на подаче. Его рвало на корте. Проиграл 2-6 6-4 6-4.",
   src:"https://www.skysports.com/tennis/news/12110/13573406/novak-djokovic-out-of-cincinnati-open-in-second-round-after-struggling-with-heat-and-humidity-against-thiago-agustin-tirante", srcName:"Sky Sports"},
  {ts:"2026-08-14 10:15", who:"Tallon Griekspoor", whoRu:"Таллон Грикспор", tour:"atp", rank:56, code:"CIN", kind:"injury", sig:"wd_mid",
   en:"withdrew from <b>Cincinnati</b> before his first-round match with an <span class='flag'>abdominal problem</span>.",
   ru:"снялся с <b>Цинциннати</b> перед первым кругом из-за <span class='flag'>живота</span>.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-13 16:45", who:"Marton Fucsovics", whoRu:"Мартон Фучович", tour:"atp", rank:122, code:"CIN", kind:"injury", sig:"retired",
   en:"retired with a <span class='flag'>back problem</span> down 1-3 to Atmane in round one of <b>Cincinnati</b>.",
   ru:"снялся с <span class='flag'>проблемой спины</span> при 1-3 против Атмана в первом круге <b>Цинциннати</b>.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-12 09:40", who:"Corentin Moutet", whoRu:"Корентен Муте", tour:"atp", rank:62, code:"CIN", kind:"injury", sig:"wd_mid",
   en:"withdrew from <b>Cincinnati</b> before round one with a <span class='flag'>wrist problem</span>.",
   ru:"снялся с <b>Цинциннати</b> перед первым кругом из-за <span class='flag'>запястья</span>.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-09 12:00", who:"Jannik Sinner", whoRu:"Янник Синнер", tour:"atp", rank:1, code:"CIN", kind:"withdrawal", sig:"wd_mid",
   en:"withdrew from <b>Cincinnati</b> because of the <span class='flag'>knee injury</span> — the first public sign the US Open was in danger.",
   ru:"снялся с <b>Цинциннати</b> из-за <span class='flag'>травмы колена</span> — первый публичный сигнал, что US Open под угрозой.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire / NYT"},
  {ts:"2026-08-09 11:00", who:"Sebastian Korda", whoRu:"Себастьян Корда", tour:"atp", rank:68, code:"USO", kind:"withdrawal", sig:"wd_pre",
   en:"is recovering from <span class='flag'>back surgery</span> and has not competed since Miami in March. Out of the US Open.",
   ru:"восстанавливается после <span class='flag'>операции на спине</span>, не играл с марта. В US Open не выступит.",
   repl:"Aleksandar Vukic", replRu:"Александар Вукич",
   src:"https://www.tennis365.com/tennis-news/us-open-withdrawal-list-2026-14-stars-out", srcName:"Tennis365"},
  {ts:"2026-08-06 19:20", who:"Frances Tiafoe", whoRu:"Фрэнсис Тиафо", tour:"atp", rank:12, code:"MTL", kind:"injury", sig:"retired",
   en:"retired with a <span class='flag'>hand problem</span> down 2-6 0-2 to Rinderknech in round three of <b>Montreal</b>.",
   ru:"снялся с <span class='flag'>проблемой кисти</span> при 2-6 0-2 против Риндеркнеша в третьем круге <b>Монреаля</b>.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-05 13:00", who:"Felix Auger-Aliassime", whoRu:"Феликс Оже-Альяссим", tour:"atp", rank:4, code:"MTL", kind:"injury", sig:"wd_mid",
   en:"withdrew from <b>Montreal</b> before round two with a <span class='flag'>back issue</span>.",
   ru:"снялся в <b>Монреале</b> перед вторым кругом из-за <span class='flag'>спины</span>.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-05 11:40", who:"Jaume Munar", whoRu:"Жауме Мунар", tour:"atp", rank:55, code:"MTL", kind:"injury", sig:"wd_mid",
   en:"withdrew from his second-round match in <b>Montreal</b> against Blockx with a <span class='flag'>back issue</span>.",
   ru:"снялся с матча второго круга в <b>Монреале</b> против Блокса из-за <span class='flag'>спины</span>.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-04 20:15", who:"Denis Shapovalov", whoRu:"Денис Шаповалов", tour:"atp", rank:48, code:"MTL", kind:"injury", sig:"retired",
   en:"retired with a <span class='flag'>leg problem</span> down 4-6 6-4 0-3 to Svajda in round one of <b>Montreal</b>.",
   ru:"снялся с <span class='flag'>проблемой ноги</span> при 4-6 6-4 0-3 против Свайды в первом круге <b>Монреаля</b>.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-01-20 09:00", who:"Lorenzo Musetti", whoRu:"Лоренцо Муссетти", tour:"atp", rank:14, code:"AO", kind:"injury", sig:"retired",
   en:"went down injured at the <b>Australian Open</b> and missed a significant stretch afterwards.",
   ru:"получил травму на <b>Australian Open</b> и пропустил заметную часть сезона.",
   src:"https://tennishead.net/jannik-sinner-told-his-us-open-withdrawal-underlines-a-bigger-issue-in-tennis-right-now/", srcName:"Tennishead"},

  /* ─────────── WTA ─────────── */
  {ts:"2026-08-24 10:40", who:"Anhelina Kalinina", whoRu:"Ангелина Калинина", tour:"wta", rank:51, code:"MTY", kind:"injury", sig:"wd_mid",
   en:"withdrew from <b>Monterrey</b> before her first-round match with a <span class='flag'>back problem</span>.",
   ru:"снялась с <b>Монтеррея</b> перед матчем первого круга из-за <span class='flag'>спины</span>.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-07-31 12:00", who:"Victoria Mboko", whoRu:"Виктория Мбоко", tour:"wta", rank:15, code:"USO", kind:"withdrawal", sig:"wd_pre",
   en:"is out of the <b>US Open</b> with a <span class='flag'>left knee injury</span> that has cost her the entire North American swing.",
   ru:"вне <b>US Open</b> из-за <span class='flag'>травмы левого колена</span>, из-за которой пропустила всю американскую серию.",
   repl:"Mananchaya Sawangkaew", replRu:"Мананчая Савангкау",
   src:"https://www.tennis365.com/tennis-news/us-open-withdrawal-list-2026-14-stars-out", srcName:"Tennis365"},
  {ts:"2026-08-22 11:50", who:"Hailey Baptiste", whoRu:"Хейли Баптист", tour:"wta", rank:37, code:"USO", kind:"withdrawal", sig:"wd_pre",
   en:"is done for the season after tearing her <span class='flag'>left ACL and meniscus</span> at Roland Garros. Out of the US Open.",
   ru:"завершила сезон после разрыва <span class='flag'>передней крестообразной связки и мениска</span> левого колена на Ролан Гаррос. В US Open не выступит.",
   repl:"Kaitlin Quevedo", replRu:"Кейтлин Кеведо",
   src:"https://www.tennis365.com/tennis-news/us-open-withdrawal-list-2026-14-stars-out", srcName:"Tennis365"},
  {ts:"2026-08-22 11:40", who:"Jaqueline Cristian", whoRu:"Жаклин Кристиан", tour:"wta", rank:44, code:"USO", kind:"withdrawal", sig:"wd_pre",
   en:"withdrew from the <b>US Open</b> entry list.",
   ru:"снялась с заявки на <b>US Open</b>.",
   repl:"Darja Vidmanova", replRu:"Дарья Видманова",
   src:"https://www.tennis365.com/tennis-news/us-open-withdrawal-list-2026-14-stars-out", srcName:"Tennis365"},
  {ts:"2026-08-22 11:30", who:"Emma Raducanu", whoRu:"Эмма Радукану", tour:"wta", rank:70, code:"USO", kind:"withdrawal", sig:"wd_mid",
   en:"withdrew from the <b>US Open</b> with an ongoing <span class='flag'>leg injury</span>.",
   ru:"снялась с <b>US Open</b> из-за продолжающейся <span class='flag'>травмы ноги</span>.",
   repl:"Anna Blinkova", replRu:"Анна Блинкова",
   src:"https://www.tennis365.com/tennis-news/us-open-withdrawal-list-2026-14-stars-out", srcName:"Tennis365"},
  {ts:"2026-08-22 11:20", who:"Laura Siegemund", whoRu:"Лаура Зигемунд", tour:"wta", rank:102, code:"USO", kind:"withdrawal", sig:"wd_pre",
   en:"withdrew from the <b>US Open</b> entry list.",
   ru:"снялась с заявки на <b>US Open</b>.",
   repl:"Nadia Podoroska", replRu:"Надя Подороска",
   src:"https://www.tennis365.com/tennis-news/us-open-withdrawal-list-2026-14-stars-out", srcName:"Tennis365"},
  {ts:"2026-08-22 11:10", who:"Ajla Tomljanovic", whoRu:"Айла Томлянович", tour:"wta", rank:103, code:"USO", kind:"withdrawal", sig:"wd_pre",
   en:"withdrew from the <b>US Open</b> entry list.",
   ru:"снялась с заявки на <b>US Open</b>.",
   repl:"Ella Seidel", replRu:"Элла Зайдель",
   src:"https://www.tennis365.com/tennis-news/us-open-withdrawal-list-2026-14-stars-out", srcName:"Tennis365"},
  {ts:"2026-08-22 11:00", who:"Varvara Gracheva", whoRu:"Варвара Грачёва", tour:"wta", rank:148, code:"USO", kind:"withdrawal", sig:"wd_pre",
   en:"withdrew from the <b>US Open</b> entry list.",
   ru:"снялась с заявки на <b>US Open</b>.",
   repl:"Anastasia Zakharova", replRu:"Анастасия Захарова",
   src:"https://www.tennis365.com/tennis-news/us-open-withdrawal-list-2026-14-stars-out", srcName:"Tennis365"},
  {ts:"2026-08-22 10:50", who:"Jil Teichmann", whoRu:"Джил Тайхманн", tour:"wta", rank:175, code:"USO", kind:"withdrawal", sig:"wd_pre",
   en:"withdrew from the <b>US Open</b> entry list.",
   ru:"снялась с заявки на <b>US Open</b>.",
   repl:"Julia Grabher", replRu:"Юлия Грабер",
   src:"https://www.tennis365.com/tennis-news/us-open-withdrawal-list-2026-14-stars-out", srcName:"Tennis365"},
  {ts:"2026-08-22 10:40", who:"Irina-Camelia Begu", whoRu:"Ирина-Камелия Бегу", tour:"wta", rank:462, code:"USO", kind:"withdrawal", sig:"wd_mid",
   en:"withdrew from the <b>US Open</b> with <span class='flag'>left knee</span> problems.",
   ru:"снялась с <b>US Open</b> из-за проблем с <span class='flag'>левым коленом</span>.",
   repl:"Elsa Jacquemot", replRu:"Эльза Жакмо",
   src:"https://www.tennis365.com/tennis-news/us-open-withdrawal-list-2026-14-stars-out", srcName:"Tennis365"},
  {ts:"2026-08-20 18:20", who:"Elena Rybakina", whoRu:"Елена Рыбакина", tour:"wta", rank:2, code:"CIN", kind:"injury", sig:"retired",
   en:"retired down 1-4 to Swiatek in the <b>Cincinnati</b> quarterfinals. Reason undisclosed.",
   ru:"снялась при 1-4 против Швёнтек в четвертьфинале <b>Цинциннати</b>. Причина не раскрыта.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-18 15:30", who:"Elina Svitolina", whoRu:"Элина Свитолина", tour:"wta", rank:9, code:"CIN", kind:"injury", sig:"wd_mid",
   en:"withdrew before her third-round match in <b>Cincinnati</b> against Xiyu Wang with an <span class='flag'>ankle problem</span>.",
   ru:"снялась перед матчем третьего круга в <b>Цинциннати</b> против Ван Синьюй из-за <span class='flag'>голеностопа</span>.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-17 20:10", who:"Anna Kalinskaya", whoRu:"Анна Калинская", tour:"wta", rank:23, code:"CIN", kind:"injury", sig:"retired",
   en:"retired down 7-6(4) 1-6 0-5 to Cirstea in round three of <b>Cincinnati</b>. Reason undisclosed.",
   ru:"снялась при 7-6(4) 1-6 0-5 против Кырстя в третьем круге <b>Цинциннати</b>. Причина не раскрыта.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-16 19:00", who:"Belinda Bencic", whoRu:"Белинда Бенчич", tour:"wta", rank:12, code:"CIN", kind:"injury", sig:"retired",
   en:"retired with a <span class='flag'>hip problem</span> down 3-6 0-0 to Boisson in round two of <b>Cincinnati</b>.",
   ru:"снялась с <span class='flag'>проблемой бедра</span> при 3-6 0-0 против Буассон во втором круге <b>Цинциннати</b>.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-15 17:25", who:"Elena-Gabriela Ruse", whoRu:"Елена-Габриэла Русе", tour:"wta", rank:64, code:"CIN", kind:"injury", sig:"retired",
   en:"retired with an <span class='flag'>ankle problem</span> down 1-6 0-3 to Eala in round two of <b>Cincinnati</b>.",
   ru:"снялась с <span class='flag'>травмой голеностопа</span> при 1-6 0-3 против Эалы во втором круге <b>Цинциннати</b>.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-14 16:50", who:"Elisabetta Cocciaretto", whoRu:"Элизабетта Коччаретто", tour:"wta", rank:67, code:"CIN", kind:"injury", sig:"illness",
   en:"retired <span class='flag'>ill</span> down 3-5 to Stefanini in round one of <b>Cincinnati</b>.",
   ru:"снялась <span class='flag'>из-за недомогания</span> при 3-5 против Стефанини в первом круге <b>Цинциннати</b>.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-14 14:20", who:"Maria Timofeeva", whoRu:"Мария Тимофеева", tour:"wta", rank:86, code:"CIN", kind:"injury", sig:"illness",
   en:"retired <span class='flag'>ill</span> down 0-6 0-3 to Xiyu Wang in round one of <b>Cincinnati</b>.",
   ru:"снялась <span class='flag'>из-за недомогания</span> при 0-6 0-3 против Ван Синьюй в первом круге <b>Цинциннати</b>.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-12 11:15", who:"Naomi Osaka", whoRu:"Наоми Осака", tour:"wta", rank:13, code:"CIN", kind:"withdrawal", sig:"rest",
   en:"withdrew from <b>Cincinnati</b> before her second-round match, listed as rest.",
   ru:"снялась с <b>Цинциннати</b> перед матчем второго круга, причина указана как отдых.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-11 18:40", who:"Belinda Bencic", whoRu:"Белинда Бенчич", tour:"wta", rank:12, code:"TOR", kind:"injury", sig:"wd_mid",
   en:"withdrew from her <b>Toronto</b> quarterfinal against Gauff with a <span class='flag'>hip problem</span>.",
   ru:"снялась с четвертьфинала <b>Торонто</b> против Гауфф из-за <span class='flag'>бедра</span>.",
   src:"https://www.rotowire.com/tennis/news.php?view=injuries", srcName:"RotoWire"},
  {ts:"2026-08-08 12:00", who:"Beatriz Haddad Maia", whoRu:"Беатрис Аддад Майя", tour:"wta", rank:154, code:"USO", kind:"condition", sig:"condition", out:true,
   en:"announced she will not play again in 2026 and will return in 2027 on a protected ranking, after a 4-19 season and eight straight losses.",
   ru:"объявила, что не сыграет до конца 2026 года и вернётся в 2027-м по защищённому рейтингу — после сезона 4-19 и восьми поражений подряд.",
   src:"https://www.wtatennis.com/news/4556449/haddad-maia-announces-break-from-tennis-it-hasnt-been-easy", srcName:"wtatennis.com"},
  {ts:"2026-04-08 10:00", who:"Qinwen Zheng", whoRu:"Чжэн Циньвэнь", tour:"wta", rank:121, code:"STU", kind:"withdrawal", sig:"wd_mid",
   en:"withdrew from <b>Stuttgart</b> injured, her third event of a season that began in February in Doha after <span class='flag'>right-elbow surgery</span>.",
   ru:"снялась со <b>Штутгарта</b> из-за травмы. Это был третий турнир сезона, который она начала в феврале в Дохе после <span class='flag'>операции на правом локте</span>.",
   repl:"Alexandra Eala", replRu:"Александра Эала",
   src:"https://english.news.cn/20260408/95a84e05a1584657992e68ffb2fd6d34/c.html", srcName:"Xinhua"},
];

/* Кто подтверждён в основной сетке US Open 2026 (посев / PR / вошедшие вместо снявшихся) —
   по официальным спискам турнира. Число — номер посева. */
const DRAW = {
  seeds:{
    "Carlos Alcaraz":2, "Felix Auger-Aliassime":3, "Novak Djokovic":4, "Frances Tiafoe":11,
    "Lorenzo Musetti":13, "Casper Ruud":19,
    "Elena Rybakina":2, "Elina Svitolina":9, "Belinda Bencic":12, "Naomi Osaka":13,
    "Anna Kalinskaya":21,
  },
  other:["Juncheng Shang", "Bonzi / Bellucci"],
  /* Отсечка прямого попадания в основную сетку по заявке от 20 июля 2026:
     замены доходили до №107-108, поэтому рейтинг до ~104 — почти наверняка основная сетка. */
  cutoff:104,
};
